name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Print log level
      run: echo "Log level: ${{ github.event.inputs.logLevel }}"

    - name: Print tags
      run: echo "Tags: ${{ github.event.inputs.tags }}"

    - name: Print environment
      run: echo "Environment: ${{ github.event.inputs.environment }}"